In [26]:
import pandas as pd
import math

In [4]:
# def compare(df1,df2):

In [5]:
df1=pd.read_excel("america_solutions_store_mapping.xlsx")
df2=pd.read_excel("india_infra_store_mapping.xlsx")
df1

,Store_ID,Store_Name,City,State,Latitude,Longitude,Store_Size_sqft,Monthly_Revenue_INR,Monthly_Rent_INR,Employees,Monthly_Footfall,Avg_Order_Value_INR,Opening_Year
0,AMS001,AMS_Store_1,Delhi,Delhi,28.608408,77.172531,2643,2562968,639281,7,8416,4111,2019
1,AMS002,AMS_Store_2,Bengaluru,Karnataka,12.967447,77.602103,4880,3378010,219563,19,3284,4416,2017
2,AMS003,AMS_Store_3,Pune,Maharashtra,18.492556,73.860073,3167,3605061,804068,19,2911,3389,2023
3,AMS004,AMS_Store_4,Ahmedabad,Gujarat,23.012743,72.598340,3774,5683482,251124,9,8822,3843,2021
4,AMS005,AMS_Store_5,Kolkata,West Bengal,22.538571,88.332573,2944,6450305,361662,7,4511,1254,2021
5,AMS006,AMS_Store_6,Pune,Maharashtra,18.481072,73.837051,1817,5204953,419842,24,7087,2856,2020
6,AMS007,AMS_Store_7,Pune,Maharashtra,18.514870,73.858845,2122,2399157,747320,11,8760,3327,2020
7,AMS008,AMS_Store_8,Chennai,Tamil Nadu,13.036620,80.244669,3245,2120059,697509,10,3790,2944,2019
8,AMS009,AMS_Store_9,Ahmedabad,Gujarat,23.027059,72.564978,3348,6079552,238688,14,7635,2583,2016
9,AMS010,AMS_Store_10,Hyderabad,Telangana,17.377375,78.453139,1675,6530232,697118,11,7049,989,2022
10,AMS011,AMS_Store_11,Ahmedabad,Gujarat,23.060165,72.582369,1890,3109287,348681,21,3294,3281,2014
11,AMS012,AMS_Store_12,Mumbai,Maharashtra,19.032543,72.840866,1790,2151749,217270,8,3235,2424,2023
12,AMS013,AMS_Store_13,Kolkata,West Bengal,22.532774,88.401950,3146,6463989,317503,9,1785,2118,2022
13,AMS014,AMS_Store_14,Hyderabad,Telangana,17.342004,78.480291,3562,6925666,776619,6,5163,2802,2015
14,AMS015,AMS_Store_15,Kolkata,West Bengal,22.548749,88.333707,1665,5777903,614904,25,6097,1639,2022
15,AMS016,AMS_Store_16,Kolkata,West Bengal,22.554593,88.353963,4844,2760324,853031,17,7111,1048,2020
16,AMS017,AMS_Store_17,Chennai,Tamil Nadu,13.093581,80.308903,2409,6142835,742642,23,7291,2808,2017
17,AMS018,AMS_Store_18,Kolkata,West Bengal,22.580740,88.338691,3096,3579520,204849,14,5453,1210,2022
18,AMS019,AMS_Store_19,Kolkata,West Bengal,22.570436,88.354103,4538,7099001,742471,8,1739,3193,2019
19,AMS020,AMS_Store_20,Kolkata,West Bengal,22.620106,88.411188,2970,6142547,266386,18,6502,3371,2018

In [6]:
df2

,Store_ID,Store_Name,City,State,Latitude,Longitude,Store_Size_sqft,Monthly_Revenue_INR,Monthly_Rent_INR,Employees,Monthly_Footfall,Avg_Order_Value_INR,Opening_Year
0,IIN001,IIN_Store_1,Ahmedabad,Gujarat,22.992385,72.617044,1811,6823253,555856,16,8233,2366,2016
1,IIN002,IIN_Store_2,Bengaluru,Karnataka,12.989751,77.602609,3246,2542624,685983,22,7653,3764,2017
2,IIN003,IIN_Store_3,Hyderabad,Telangana,17.400806,78.500609,3807,6716504,659735,23,5697,3486,2015
3,IIN004,IIN_Store_4,Chennai,Tamil Nadu,13.041166,80.304830,2846,4958845,710100,10,5821,1473,2018
4,IIN005,IIN_Store_5,Mumbai,Maharashtra,19.105805,72.889368,4202,7169666,865296,8,7080,1825,2014
5,IIN006,IIN_Store_6,Bengaluru,Karnataka,12.983636,77.597864,3331,2344458,427133,12,6077,1180,2019
6,IIN007,IIN_Store_7,Mumbai,Maharashtra,19.103097,72.855935,3817,5282698,443212,22,8779,3799,2023
7,IIN008,IIN_Store_8,Bengaluru,Karnataka,12.965283,77.547323,4847,6281434,616155,10,3498,3033,2018
8,IIN009,IIN_Store_9,Delhi,Delhi,28.592469,77.224082,1951,4182571,313215,9,7252,1552,2020
9,IIN010,IIN_Store_10,Bengaluru,Karnataka,12.944342,77.596655,4137,6788647,371583,24,5870,1714,2021
10,IIN011,IIN_Store_11,Hyderabad,Telangana,17.337137,78.460810,2920,4778330,429186,17,6346,1360,2015
11,IIN012,IIN_Store_12,Bengaluru,Karnataka,12.996770,77.601840,4478,5968671,335504,11,7127,4227,2018
12,IIN013,IIN_Store_13,Mumbai,Maharashtra,19.087519,72.906823,1983,7346904,367566,12,7693,3920,2021
13,IIN014,IIN_Store_14,Delhi,Delhi,28.637934,77.241167,2454,4077364,766384,25,3766,3601,2022
14,IIN015,IIN_Store_15,Mumbai,Maharashtra,19.052075,72.858382,4529,3592369,805136,13,6239,1136,2020
15,IIN016,IIN_Store_16,Pune,Maharashtra,18.538654,73.897679,1542,7564342,467488,19,2058,2030,2020
16,IIN017,IIN_Store_17,Chennai,Tamil Nadu,13.058769,80.292909,3731,4688113,388143,12,5441,2249,2014
17,IIN018,IIN_Store_18,Bengaluru,Karnataka,12.983920,77.636702,2725,2174123,384295,10,7546,2401,2014
18,IIN019,IIN_Store_19,Bengaluru,Karnataka,12.984580,77.629879,1921,2692439,454547,6,7158,3447,2023
19,IIN020,IIN_Store_20,Ahmedabad,Gujarat,22.976871,72.560962,3479,2983075,696715,7,8431,1200,2015

In [ ]:
def compare(a,b):
    if a>b:
        return a
    elif a<b:
        return b
    else:
        return avg = statistics.mean([12, 34])
print(avg)

In [ ]:
import statistics

In [28]:
result={}
for i in df1.columns:
    new_list=[]  
    for v1,v2 in zip(df1[i].values,df2[i].values):
            recent=compare(v1, v2)
            new_list.append(recent)
    #df=pd.DataFrame(new_list,columns=[i])
    result[i]=new_list
df=pd.DataFrame(result)
df

AttributeError: module 'math' has no attribute 'avg'